In [1]:
a=[1,5,9]

In [2]:
a

[1, 5, 9]

In [3]:
import numpy as np

In [4]:
np.array(a)

array([1, 5, 9])

In [13]:
b=  [[4,6,7],[8,6,8]]

In [14]:
b

[[4, 6, 7], [8, 6, 8]]

In [15]:
np. array(b)

array([[4, 6, 7],
       [8, 6, 8]])

In [29]:
matrice=[2,4,4],[9,0,6],[9,4,0]

In [30]:
np.array(matrice)

array([[2, 4, 4],
       [9, 0, 6],
       [9, 4, 0]])

In [31]:
np.arange(10,110,10)

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [33]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [35]:
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [10]:
import numpy as np

In [14]:
n(1,5,5)p.linspace

array([1., 2., 3., 4., 5.])

In [18]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [20]:
np.random.rand(3,4)

array([[0.19061562, 0.30723049, 0.53252402, 0.568691  ],
       [0.20227807, 0.66354611, 0.15408556, 0.53590103],
       [0.1775942 , 0.67085654, 0.57201675, 0.19255904]])

In [21]:
np.random.randn(2,4)

array([[-0.27440113, -0.33649998, -0.27488315, -1.42235594],
       [-0.1031506 ,  0.52782523, -1.13363499, -1.4978873 ]])

In [27]:
np.random.randint(10,100,9)

array([81, 21, 65, 81, 82, 20, 73, 38, 86])

In [34]:
a = np.arange(25)

In [35]:
b = np.random.randint(1,20,30)

In [37]:
b

array([ 9,  7, 19, 12,  2,  9, 12, 17, 10,  6, 10,  9,  8,  7,  5, 16,  9,
       10, 11,  8, 11,  2,  1,  9,  7, 12,  6, 12,  2, 16])

In [38]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [40]:
b.max()

19

In [41]:
a.max()

24

In [42]:
b.argmax()

2

In [44]:
b.argmin()

22

In [4]:
import numpy as np
n1=np.array([10,20,30,40,65])
n1

array([10, 20, 30, 40, 65])

In [6]:
n2=np.array([[29,40,50,60],[39,50,69,46]])
n2

array([[29, 40, 50, 60],
       [39, 50, 69, 46]])

In [8]:

n1

array([[0., 0.]])

In [9]:

n1

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
n3=np.array([10,20,30,40,50])

In [11]:
n3

array([10, 20, 30, 40, 50])

In [12]:
type(n3)

numpy.ndarray

In [13]:
np3 = np.zeros((10,10))

In [14]:
np3

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [18]:
type(np3)

numpy.ndarray

In [20]:
n4 = np.full((3,4),55)

In [21]:
n4

array([[55, 55, 55, 55],
       [55, 55, 55, 55],
       [55, 55, 55, 55]])

In [22]:
n1 = np.arange(10,30)

In [23]:
n1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29])

In [28]:
n2= np.arange(50,101,)

In [29]:
n2

array([ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,
        63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,
        76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,
        89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [40]:
n2=np.random.randint(0,6,5)

In [41]:
n2

array([1, 0, 5, 0, 5])

In [42]:
n1=np.array(([1,2,3],[4,6,7]))

In [43]:
n1.shape

(2, 3)

In [1]:
import numpy as np

In [2]:
n1= np.array([10,20,30,])
n2= np.array([40,50,60])

In [3]:
np.vstack((n1,n2))

array([[10, 20, 30],
       [40, 50, 60]])

In [4]:
n1= np.array([10,20,30,])
n2= np.array([40,50,60])

In [5]:
np.hstack((n1,n2))

array([10, 20, 30, 40, 50, 60])

In [6]:
n1= np.array([10,20,30,])
n2= np.array([40,50,60])

In [7]:
np.column_stack((n1,n2))

array([[10, 40],
       [20, 50],
       [30, 60]])

In [13]:
n1=np.array([10,20,30,40,50,60,])
n2=np.array([50,60,70,80,90,])

In [15]:
np.intersect1d(n1,n2)

array([50, 60])

In [16]:
np.setdiff1d(n1,n2)

array([10, 20, 30, 40])

In [19]:
n1 = np.array([10,20])

In [26]:
n2 = np.array([30,40])

In [28]:
np.sum([n1,n2])

100

In [29]:
np.sum([n1,n2],axis=0)

array([40, 60])

In [7]:
import numpy as np

In [8]:
n1 = np.array([10,20,30])

In [12]:
n1 + 25

array([35, 45, 55])

In [13]:
n1-5

array([ 5, 15, 25])

In [14]:
n1*10

array([100, 200, 300])

In [16]:
n1/5


array([2., 4., 6.])

In [17]:
n1=np.array([10,20,30,40,50,60,])

In [18]:
np.mean(n1)

35.0

In [19]:
np.median(n1)

35.0

In [21]:
np.std(n1)

17.07825127659933

In [28]:
n1=np.random.randint(1,50,10)

In [29]:
n1

array([22, 25, 25,  3,  6, 12, 44, 21, 14, 18])

In [30]:
np.std(n1)

11.0